const SELECTED_NAVIGATION_OPTION = 'active_navopt'
const SELECTED_MOVIE_VIEW = 'active_movie_view'
const LIKED_MOVIES_BY_USERS = 'liked_movies'

export {SELECTED_NAVIGATION_OPTION, SELECTED_MOVIE_VIEW, LIKED_MOVIES_BY_USERS}
